### ISSUE TITLE
Screenshot annotator improvements

### ISSUE THREAD

**Issue by lassoan** [SlicerLatinAmerica/SlicerTutorialMaker#14]
- [x] Aspect ratios of icons in the annotator were not correct
- [x] Add title to the annotator window (now it is just "Slicer")
- [x] There are cropping issues when using two monitors
- [x] Click position is sometimes not computed correctly
- [x] Need to be able to add text to click markers
- [x] Need to highlight the widgets as the mouse moves on the screen
- [x] At the same position there are several widgets (button or a parent frame, etc.), therefore we need a way to select which one we want the annotation to be anchored to
- [x] Runtime error:
```
Traceback (most recent call last):
  File "/Users/pieper/slicer/latest/TutorialMaker/TutorialMaker/Lib/TutorialGUI.py", line 100, in eventFilter
    self.mouse_press_event(event)
  File "/Users/pieper/slicer/latest/TutorialMaker/TutorialMaker/Lib/TutorialGUI.py", line 441, in mouse_press_event
    self.calculate_annotation()
  File "/Users/pieper/slicer/latest/TutorialMaker/TutorialMaker/Lib/TutorialGUI.py", line 480, in calculate_annotation
    x_i, y_i = wdgts_child["position"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by DouSam** [comment]
@lassoan I think not only the ratios of the icons but the images too. When the screenshot is taken, its resolution is the Slicer resolution. So, on my computer will take an ultrawide screenshot, and in my notebook a 4k screenshot. I think all the screenshots should be sized to 1080p for example.

**Comment by vmms** [comment]
@lassoan  @LuskasHusty  @enriquehdez98 
I can the latest version on an iMac computer that was not used for development and found that when taking the screenshot the entire screen is taken into account, not just the Slicer window.
For example, if Slicer is not maximized you can see that the desktop is captured in the background.
![Captura de pantalla 2024-03-18 a la(s) 20 29 31](https://github.com/SlicerLatinAmerica/TutorialMaker/assets/15926896/8a613ba7-cda7-4817-94d1-ae75b482caf7)

But if it is maximized you can still see that the Apple taskbar is captured.
![Captura de pantalla 2024-03-18 a la(s) 20 30 33](https://github.com/SlicerLatinAmerica/TutorialMaker/assets/15926896/75d18bd1-7bbe-4535-917f-2fcf37e12279)

This causes problems regarding the position of the widgets, since since they are being stored in the JSON, the relative position is captured with respect to the Slicer window and not to the position of the screen.

Even in the second image where Slicer is maximized, the annotations are out of focus due to the taskbar.

**Comment by LuskasHusty** [comment]
@vmms That is a issue with the screenshot capture tool then. I'ill look into it, until then please confirm that you are using the latest version.

**Comment by vmms** [comment]
The versions I used are:
- Slicer 5.7.0
- TutorialMaker 31-01-2024
Then, on another Mac with an extended screen the same problem happens, it even combines the two monitors
![Captura de pantalla 2024-03-19 a la(s) 9 59 24 a m  (2)](https://github.com/SlicerLatinAmerica/TutorialMaker/assets/15926896/ed9978f9-fe2f-4077-9764-1f37c478a3f3)

**Comment by DouSam** [comment]
> The versions I used are:
> 
> * Slicer 5.7.0
> * TutorialMaker 31-01-2024
>   Then, on another Mac with an extended screen the same problem happens, it even combines the two monitors
>   ![Captura de pantalla 2024-03-19 a la(s) 9 59 24 a m  (2)](https://private-user-images.githubusercontent.com/15926896/314201707-ed9978f9-fe2f-4077-9764-1f37c478a3f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4ODkzNTgsIm5iZiI6MTcxMDg4OTA1OCwicGF0aCI6Ii8xNTkyNjg5Ni8zMTQyMDE3MDctZWQ5OTc4ZjktZmUyZi00MDc3LTk3NjQtMWYzN2M0NzhhM2YzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDIyNTczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwYmFiZDdlMzQ2NjU3N2UwZWQwZGUxODgzYTU4NjgxMDMyMDNiNGIzZGIwNDlmNjllMmNmNjc1MjI5ODgxYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HF_G7dLGz-rkumud-tJqyRHR8l_bQBlHK0IszwkGrjk)

@vmms clone the extension again. One of Lucas's last commits has solved this problem!

**Comment by vmms** [comment]
@lassoan  The point: Need to be able to add text to click markers. Arrows have text, but do they need text in all annotations?

**Comment by lassoan** [comment]
Most of the time arrows will have text, but if we only want to highlight one thing in the image then it is possible that there is no text.

**Comment by vmms** [comment]
I modified the code so that when there is no text in the input field the box is not painted, but when there is text it is painted along with a box. 
![Captura de pantalla 2024-09-23 a la(s) 2 42 41 p m](https://github.com/user-attachments/assets/b5762588-f12f-4618-8e74-e6125afd0bc2)

**Comment by DouSam** [comment]
Good. Dont forget to make a commit with these changes. You can create a new branch using the updated version of the repository.

**Comment by vmms** [comment]
Now when you change the color of the arrow, the color of the accompanying text box also changes. The default color was orange. Also, I increased the limit of characters that can be written, and added a function to make the box larger and fit the text.

![Captura de pantalla 2024-09-24 a la(s) 10 52 59 a m](https://github.com/user-attachments/assets/a9009ce2-6cd0-4147-9610-ab14c6bc306a)

**Comment by DouSam** [comment]
Is the "click position" problem still occurring? I have tested here and when I put my mouse in a widget and click, the click works correctly. @vmms @spujol could you please test? See if your click in MAC is not working correctly, like, you click on a button and the annotation goes to another place.

**Comment by FatouBintou22** [comment]
@MohamedAllali and I notice that by clicking on a button, the annotation goes to another place sometimes

![Image](https://github.com/user-attachments/assets/11dca42a-ada8-4559-acf9-9e3b59defeb9)

**Comment by DouSam** [comment]
![Image](https://github.com/user-attachments/assets/ce975b6a-e21d-4d31-931a-d246aa4ade18)

**Comment by DouSam** [comment]
Hi @lassoan! We have fixed the problems listed in this issue. When you have time, test again the extension and tell us if these problems are solved and we can close this issue.
